### PR TITLE
BrickDimension now checks on UIScreen bounds

### LINKED ISSUE #13: BrickDimension.Orientation has wrong value when orientation `isFlat`
BrickDimension.Orientation doesn't work correctly when the device `isFlat`. Then it defaults to `landscape`. This should be fixed by checking the current frame's sizes

### PR DESCRIPTION
**Pull request by rubencagnie**
- Check for orientation is now done on `UIScreen.mainScreen().bounds`
- Added tests that swizzle `UIScreen.mainScreen()`

Fixes #13

### CODE REVIEW

File: Tests/Models/BrickDimensionTests.swift [hunk 1]
```diff
@@ -144,3 +155,63 @@ class BrickDimensionTests: XCTestCase {
...
+extension UIScreen {
+    @objc class func stubMainScreen() -> UIScreen {
+        return StubScreen()
+    }
+}
+
+class StubScreen: UIScreen {
+    static var horizontalSizeClass: UIUserInterfaceSizeClass = .Unspecified
+    static var verticalSizeClass: UIUserInterfaceSizeClass = .Unspecified
+    static var bounds: CGRect = CGRect(x: 0, y: 0, width: 320, height: 480)
```
Comment (klundberg) [inline Tests/Models/BrickDimensionTests.swift]: this should have a reset method that gets called in `tearDown` so that some test runs don't potentially affect others.
