### PR TITLE
Properly insert/delete items

### LINKED ISSUE #158: Wrong indexPaths are called when inserting/deleting items
When inserting/deleting items, the wrong indexPaths are called to calculate the cell's frame

### PR DESCRIPTION
**Pull request by rubencagnie**
The items that are inserted/deleted will now be properly placed in the correct atttributes location, so that the animations make much more sense

Fixes #158

### CODE REVIEW

File: Source/Layout/BrickFlowLayout.swift [hunk 1]
```diff
@@ -346,8 +316,8 @@ extension BrickFlowLayout {
         }
 
         var attributes: [UICollectionViewLayoutAttributes] = []
-        for (_, section) in sections {
-            attributes += section.layoutAttributesForElementsInRect(rect, with: zIndexer)
+        for (sectionIndex, section) in sections {
```
Comment (jay18001) [inline Source/Layout/BrickFlowLayout.swift]: can we use `sections.forEach { ... `

File: Source/Layout/BrickFlowLayout.swift [hunk 2]
```diff
@@ -693,9 +663,23 @@ extension BrickFlowLayout {
             }
         }
 
-        isUpdating = true
+        if (insertedIndexPaths.count + deletedIndexPaths.count) > 0 {
+            zIndexer.reset(for: self)
+            for (sectionIndex, section) in sections! {
```
Comment (jay18001) [inline Source/Layout/BrickFlowLayout.swift]: Can we change force unwrap to an `if let`

File: Source/Layout/BrickLayoutSection.swift [hunk 3]
```diff
@@ -137,36 +137,49 @@ internal class BrickLayoutSection {
...
-            self.numberOfItems = numberOfItems
-            while attributes.count > numberOfItems {
-                let lastIndex = attributes.keys.max()! // Max Element will always be available based on this logic (difference is smaller than 0, so there are values available)
-                let last = attributes[lastIndex]!
-                removedAttributes?(last, last.frame)
-                
-                attributes.removeValue(forKey: lastIndex)
+        let sortedDeleted = deleted.sorted(by: >)
+
+        for index in sortedDeleted {
```
Comment (jay18001) [inline Source/Layout/BrickLayoutSection.swift]: same here about the `.forEach`

File: Source/Cells/BrickCell.swift [hunk 4]
```diff
@@ -206,8 +206,17 @@ open class BrickCell: BaseBrickCell {
 
         let preferred = layoutAttributes.copy() as! UICollectionViewLayoutAttributes
 
-        let size = CGSize(width: layoutAttributes.frame.width, height: self.heightForBrickView(withWidth: layoutAttributes.frame.width))
-        preferred.frame.size = size
+
```
Comment (jay18001) [inline Source/Cells/BrickCell.swift]: Extra new line

File: Source/Layout/BrickLayoutSection.swift [hunk 5]
```diff
@@ -137,36 +137,49 @@ internal class BrickLayoutSection {
...
-            updateAttributeIdentifiers(targetStartIndex: &startIndex)
-            createOrUpdateCells(from: startIndex, invalidate: true, updatedAttributes: nil)
+
+            startIndexToUpdate = min(index, startIndexToUpdate)
         }
+
+
+        let sortedInserted = inserted.sorted(by: <)
+
+        for index in sortedInserted {
```
Comment (jay18001) [inline Source/Layout/BrickLayoutSection.swift]: Same

File: Source/Cells/BrickCell.swift (hunk 4 above)
Comment (rubencagnie) [inline Source/Cells/BrickCell.swift]: Fixed

File: Source/Layout/BrickFlowLayout.swift (hunk 1 above)
Comment (rubencagnie) [inline Source/Layout/BrickFlowLayout.swift]: Logic has a reference to to `self` (`_collectionView` & `zIndexer`)

File: Source/Layout/BrickFlowLayout.swift (hunk 2 above)
Comment (rubencagnie) [inline Source/Layout/BrickFlowLayout.swift]: It's OK to force unwrap sections. Without them being initialized, there wouldn't be any insert/delete possible
I've added a comment to describe this
