### PR TITLE
Sticky footer was wrongly calculated

### LINKED ISSUE #8: Sticky Footer for Sections didn't calculate correctly
In the demo-app, the Sticky Footer with sections is broken
The calculation for the bricks within the section are wrong

### PR DESCRIPTION
**Pull request by rubencagnie**
- StickyFooterLayoutBehavior was still using `frame` instead of `originalFrame` for the calculations
- BrickLayoutSection also needs to take previously calculated bricks into account if the origin had already changed
- Fixed Demo App when enabling/disabling behaviors
- Test

Fixes #8

### CODE REVIEW

File: Example/Source/Examples/BaseBrickController.swift [hunk 1]
```diff
@@ -15,21 +15,21 @@ class BaseBrickController: BrickViewController {
...
-            updateBehavior()
+            updateBehavior(false)
         }
     }
 
     override func viewWillAppear(animated: Bool) {
         super.viewWillAppear(animated)
         self.view.backgroundColor = .brickBackground
-        updateBehavior()
+        updateBehavior(true)
```
Comment (klundberg) [inline Example/Source/Examples/BaseBrickController.swift]: It's not clear to me reading this code what the boolean flag does at the call site. It might be clearer to say something like this so that others who read this code know when the flag should be true or not:
```swift
updateBehavior(isViewAppearing: true)
```
Conversely, it might also be simpler to just put the `self.brickCollectionView.invalidateBricks()` wherever you'd pass false, instead of putting it in `updateBehavior()`. That way the flag isn't even necessary.
