### PR TITLE
Fixed a bug that prevented the SnapToPointLayoutBehavior from filteri…

### LINKED ISSUE #82: SnapToPointLayoutBehavior does not always ignore the overall CollectionBrick section
If the only layout attribute in a `CollectionBrick` (with `SnapToPointLayputBehavior` added) is the layout for the overall brick, the attribute is not ignored before the collectionView content offset is calculated. This can occur if `resetCollectionViewContentInset` is called before the widths of the collection brick's bricks are calculated.

### PR DESCRIPTION
**Pull request by willspurgeon**
…ng out the enclosing CollectionBrick layout attribute before calculating offsets. Fixes #82

### CODE REVIEW

File: Source/Behaviors/SnapToPointLayoutBehavior.swift [hunk 1]
```diff
@@ -95,40 +95,58 @@ public class SnapToPointLayoutBehavior: BrickLayoutBehavior {
         resetCollectionViewContentInset(collectionViewLayout)
     }
 
+    internal func getFilteredAttributes(layout collectionViewLayout: UICollectionViewLayout, frame: CGRect) -> [BrickLayoutAttributes] {
```
Comment (rubencagnie) [inline Source/Behaviors/SnapToPointLayoutBehavior.swift]: I don't like the `get` prefix. That's very java-like
Please rename to
`filteredAttributes(layout collectionViewLayout: UICollectionViewLayout, frame: CGRect) -> [BrickLayoutAttributes]`

File: Source/Behaviors/SnapToPointLayoutBehavior.swift [hunk 2]
```diff
@@ -95,40 +95,58 @@ public class SnapToPointLayoutBehavior: BrickLayoutBehavior {
...
+        guard !filteredAttributes.isEmpty else {
             return
         }
 
         originalTopContentInset = collectionViewLayout.collectionView!.contentInset.top
 
         switch scrollDirection {
         case .Horizontal(let scrollLocation):
-            let firstAttributes = attributes.minElement {
+            let firstAttribute = filteredAttributes.minElement {
```
Comment (rubencagnie) [inline Source/Behaviors/SnapToPointLayoutBehavior.swift]: No need to rename `firstAttributes` to `firstAttribute`. The object contains `BrickLayoutAttributes` (with a S)

File: Tests/Behaviors/SnapToPointLayoutBehaviorTests.swift [hunk 3]
```diff
@@ -356,6 +356,54 @@ class SnapToPointLayoutBehaviorTests: XCTestCase {
...
     }
 
+    func testAttributesFilter() {
+        let behavior = SnapToPointLayoutBehavior(scrollDirection: .Horizontal(.Center))
 
+        let layout = UICollectionViewLayout()
+        behavior.getFilteredAttributes(layout: layout, frame: CGRect(x: 0, y: 0, width: 480, height: 360))
 
+
+        let collection = CollectionViewController()
```
Comment (rubencagnie) [inline Tests/Behaviors/SnapToPointLayoutBehaviorTests.swift]: This test can be much simpeler by not using a `CollectionViewController`

Checkout `BrickCollectionViewTests:testWithImageInCollectionBrick`
```
        let section1 = BrickSection(bricks: [
            ImageBrick(width: .Ratio(ratio: 1/4), height: .Ratio(ratio: 1), dataSource: ImageBrickModel(image: image, contentMode: .ScaleAspectFill)),
            ])

        let section = BrickSection(backgroundColor: .whiteColor(), bricks: [
            CollectionBrick("Collection 1", backgroundColor: .orangeColor(), scrollDirection: .Horizontal, dataSource: CollectionBrickCellModel(section: section1), brickTypes: [ImageBrick.self]),
            ])
        brickView.setupSectionAndLayout(section)

        let cell1 = brickView.cellForItemAtIndexPath(NSIndexPath(forItem: 0, inSection: 1))
        XCTAssertEqual(cell1?.frame, CGRect(x: 0, y: 0, width: 320, height: 80))
```

Comment (rubencagnie) [inline Tests/Behaviors/SnapToPointLayoutBehaviorTests.swift]: There is also in `CollectionBrickCellModel` a `configureHandler` that you can use to add the behavior
