### PR TITLE
Fixed performance of height recalculation

### LINKED ISSUE #63: Better logging
BrickKit should have better logging to debug issues

### PR DESCRIPTION
**Pull request by rubencagnie**
- Fixed performance of height recalculation
- Added logging

Fixes #63

### CODE REVIEW

File: Source/Layout/BrickFlowLayout.swift [hunk 1]
```diff
@@ -284,7 +298,27 @@ extension BrickFlowLayout {
         return contentSize
     }
 
+    func updateDirtyBricks(updatedAttributes: @escaping OnAttributesUpdatedHandler) {
+        for (section, item) in dirtyMap {
+            // This can be unwrapped safely
+            // because the sections that are in the dirtyMap should be there
```
Comment (jay18001) [inline Source/Layout/BrickFlowLayout.swift]: `should` what happens if they aren't there

File: Source/Utils/BrickLogger.swift [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+//  BrickKit
+//
+//  Created by Ruben Cagnie on 8/23/17.
+//  Copyright © 2017 Wayfair. All rights reserved.
+//
+
+import UIKit
+
+public protocol BrickLoggable {
+    func logError(message: @escaping @autoclosure() -> String, file: String, lineNumber: Int, function: String)
```
Comment (jay18001) [inline Source/Utils/BrickLogger.swift]: We should drop the message pram label

File: Source/Layout/BrickFlowLayout.swift (hunk 1 above)
Comment (rubencagnie) [reply Source/Layout/BrickFlowLayout.swift]: It's not possible that they aren't because they are set within below function. So there is never a case that they aren't there

`open override func shouldInvalidateLayout(forPreferredLayoutAttributes preferredAttributes: UICollectionViewLayoutAttributes, withOriginalAttributes originalAttributes: UICollectionViewLayoutAttributes) -> Bool`
