### PR TITLE
Fixed the invalidating heights animation

### LINKED ISSUE #153: Invalidating heights is not animated correctly
When invalidating a height, the animation is not correct. First the brick that changes height is not animated when the height changes, but the bricks below, will animate to their new location

### PR DESCRIPTION
**Pull request by jay18001**
Closed #153

### CODE REVIEW

File: Source/Cells/BrickCell.swift [hunk 1]
```diff
@@ -218,6 +218,12 @@ open class BrickCell: BaseBrickCell {
         _brick.brickCellTapDelegate?.didTapBrickCell(self)
     }
 
+    open override func apply(_ layoutAttributes: UICollectionViewLayoutAttributes) {
+        UIView.animate(withDuration: UIView.inheritedAnimationDuration, animations: {
```
Comment (rubencagnie) [inline Source/Cells/BrickCell.swift]: There shouldn't be a `UIView.animate` for every apply

File: Example/BrickKit-Example.xcodeproj/xcshareddata/xcschemes/BrickApp-iOS.xcscheme [hunk 2]
```diff
@@ -26,6 +26,7 @@
       buildConfiguration = "Debug"
       selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
       selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
+      language = ""
```
Comment (rubencagnie) [inline Example/BrickKit-Example.xcodeproj/xcshareddata/xcschemes/BrickApp-iOS.xcscheme]: Is this needed?

File: Example/Source/Examples/Interactive/InvalidateHeightViewController.swift [hunk 3]
```diff
@@ -55,12 +53,15 @@ class InvalidateHeightViewController: BrickViewController, HasTitle {
...
+        let newHeight: BrickDimension
         switch brick.height {
-        case .fixed(_): brick.height = .auto(estimate: .fixed(size: 100))
-        default: brick.height = .fixed(size: 200)
+        case .fixed(_): newHeight = .auto(estimate: .fixed(size: 100))
+        default: newHeight = .fixed(size: 200)
         }
+        
+        let size = BrickSize(width: .ratio(ratio: 1), height: newHeight)
+        self.brickCollectionView.resizeBrick(with: BrickIdentifiers.titleLabel, newSize: size)
```
Comment (rubencagnie) [inline Example/Source/Examples/Interactive/InvalidateHeightViewController.swift]: Can we wrap it in an animation block? That way it's a good documentation on how to animate this

File: Source/ViewControllers/BrickCollectionView.swift [hunk 4]
```diff
@@ -234,7 +234,27 @@ open class BrickCollectionView: UICollectionView {
             self.collectionViewLayout.invalidateLayout(with: BrickLayoutInvalidationContext(type: .invalidate))
         }, completion: completion)
     }
-
+    
+    open func resizeBrick(with identifier: String, newSize: BrickSize, completion: ((Bool) -> Void)? = nil)  {
```
Comment (rubencagnie) [inline Source/ViewControllers/BrickCollectionView.swift]: Can we also supply an optional index as well?

File: Source/ViewControllers/BrickCollectionView.swift [hunk 5]
```diff
@@ -234,7 +234,27 @@ open class BrickCollectionView: UICollectionView {
...
+        self.performBatchUpdates({
+            if let indexPath = self.indexPathsForBricksWithIdentifier(identifier).first {
+                let brick = self.brick(at: indexPath)
+                brick.size = newSize
+            }
+            
+            self.collectionViewLayout.invalidateLayout(with: BrickLayoutInvalidationContext(type: .invalidate))
```
Comment (rubencagnie) [inline Source/ViewControllers/BrickCollectionView.swift]: Why is this needed?

File: Source/ViewControllers/BrickCollectionView.swift [hunk 6]
```diff
@@ -234,7 +234,27 @@ open class BrickCollectionView: UICollectionView {
             self.collectionViewLayout.invalidateLayout(with: BrickLayoutInvalidationContext(type: .invalidate))
         }, completion: completion)
     }
-
+    
+    open func resizeBrick(with identifier: String, newSize: BrickSize, completion: ((Bool) -> Void)? = nil)  {
+        self.performBatchUpdates({
+            if let indexPath = self.indexPathsForBricksWithIdentifier(identifier).first {
```
Comment (rubencagnie) [inline Source/ViewControllers/BrickCollectionView.swift]: We should hold a reference to the fetched indexPahts, so we can use them later. Also, why are we only doing first?

File: Example/Source/Examples/Interactive/InvalidateHeightViewController.swift (hunk 3 above)
Comment (klundberg) [inline Example/Source/Examples/Interactive/InvalidateHeightViewController.swift]: I think the idea is that its already implicitly animated since it delegates to performUpdates function which also does this. wrapping it in an animation block doesn't have any effect if you just want the default animation parameters

File: Source/Cells/BrickCell.swift [hunk 7]
```diff
@@ -213,17 +214,17 @@ open class BrickCell: BaseBrickCell {
...
     }
-
+    
     open override func preferredLayoutAttributesFitting(_ layoutAttributes: UICollectionViewLayoutAttributes) -> UICollectionViewLayoutAttributes {
         guard self._brick.height.isEstimate(withValue: nil) else {
             return layoutAttributes
         }
 
-        let preferred = layoutAttributes.copy() as! UICollectionViewLayoutAttributes
+        let preferred = layoutAttributes
```
Comment (klundberg) [inline Source/Cells/BrickCell.swift]: Should we revert this?

File: Source/ViewControllers/BrickCollectionView.swift (hunk 6 above)
Comment (jay18001) [inline Source/ViewControllers/BrickCollectionView.swift]: The index path may have changed after the invalidateLayout so we have to get it again

File: Example/Source/Examples/Interactive/InvalidateHeightViewController.swift (hunk 3 above)
Comment (jay18001) [inline Example/Source/Examples/Interactive/InvalidateHeightViewController.swift]: Correct, there is a default animation, warping it in an animation block only changes the the duration.

File: Example/BrickKit-Example.xcodeproj/xcshareddata/xcschemes/BrickApp-iOS.xcscheme (hunk 2 above)
Comment (jay18001) [inline Example/BrickKit-Example.xcodeproj/xcshareddata/xcschemes/BrickApp-iOS.xcscheme]: I think this is a artifact from Xcode 9

File: Source/Cells/BrickCell.swift (hunk 7 above)
Comment (jay18001) [inline Source/Cells/BrickCell.swift]: Doesn't seem to have any side effects by the looks of it

File: Source/ViewControllers/BrickCollectionView.swift (hunk 5 above)
Comment (jay18001) [inline Source/ViewControllers/BrickCollectionView.swift]: It's not, removing

File: Source/ViewControllers/BrickCollectionView.swift (hunk 4 above)
Comment (jay18001) [inline Source/ViewControllers/BrickCollectionView.swift]: Sure

File: Example/Source/Examples/Interactive/InvalidateHeightViewController.swift (hunk 3 above)
Comment (rubencagnie) [inline Example/Source/Examples/Interactive/InvalidateHeightViewController.swift]: I understand, but it would be good to demonstrate how to change the duration (and animation options)

File: Source/ViewControllers/BrickCollectionView.swift (hunk 6 above)
Comment (rubencagnie) [inline Source/ViewControllers/BrickCollectionView.swift]: Why would the indexPaths have changed?

Comment (jay18001) [inline Source/ViewControllers/BrickCollectionView.swift]: It would because we we calling invalidate layout but now I don't need that that's no longer an issue

File: Example/Source/Examples/Interactive/InvalidateHeightViewController.swift (hunk 3 above)
Comment (jay18001) [inline Example/Source/Examples/Interactive/InvalidateHeightViewController.swift]: Ok, no big deal

File: Source/Bricks/Image/ImageBrick.swift [hunk 8]
```diff
@@ -149,7 +149,7 @@ open class ImageBrickCell: GenericBrickCell, Bricklike, AsynchronousResizableCel
     fileprivate var imageLoaded = false
     fileprivate var currentImageURL: URL? = nil
 
-    @IBOutlet public weak var imageView: UIImageView!
+    @IBOutlet weak var imageView: UIImageView!
```
Comment (rubencagnie) [inline Source/Bricks/Image/ImageBrick.swift]: Why was this changed?
