### PR TITLE
Collection bricks with fixed heights were infinitely resizing.

### LINKED ISSUE #109: CollectionBrick issues with height sizing
If a collection brick has a non-automatic height estimate, it will try to update its height anyway.  This causes bugs with two collection bricks on the same screen, and nested collection bricks which infinitely loop when adjusting height.

### PR DESCRIPTION
**Pull request by thevwu**
This is an issue when you have an outer collection brick with a fixed height, and an inner collection brick with an automatic height.  When scrolling the outer collection brick, the inner collection brick will keep resizing itself because the outer collection brick is also resizing itself.  This merge makes it so that if a collection brick has a fixed height, it will not try to resize itself.

Fixes #109

### CODE REVIEW

File: Source/Bricks/Collection/CollectionBrick.swift [hunk 1]
```diff
@@ -145,6 +145,11 @@ public class CollectionBrickCell: BrickCell, Bricklike, AsynchronousResizableCel
             return super.preferredLayoutAttributesFittingAttributes(layoutAttributes)
         }
         
+        guard self._brick.height.isEstimate else {
```
Comment (jay18001) [inline Source/Bricks/Collection/CollectionBrick.swift]: Do we need `self.` here?
